### ISSUE TITLE
Add additional methods for standard pipeline support

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-chargify-source#2]
| Table Name                                         | Schema Name | Method             |
|----------------------------------------------------|-------------|--------------------|
|customers |chargify |listCustomers |
|invoice_charges  |chargify     |listInvoiceCharges        |
|invoice_payments |chargify     |listInvoicePayments        |
|invoices                 |chargify     |listInvoices        |
|payment_profiles |chargify     |listPaymentProfiles |
|subscriptions       |chargify     |listSubscriptions   |
|transactions         |chargify     |listTransactions    |

Currently there are two ways to implement the `invoice_charges` and `invoice_payments` fields.

1) When `invoice_id: getAll`, `invoices` endpoint is first hit and iterated through to generate a list of `invoice_ids that are then passed into the appropriate second endpoint (either charges or payments --- see https://github.com/aries-data/aries-activity-github-source/blob/master/lib/index.js#L180 for example )

2) Only the `invoices` endpoint is hit and all fields except for `charges` and `payments` are filtered out (with the invoice `id` field renamed to `invoice_id`. These objects are then return in a top level array.

**Comment by benjamingregory** [comment]
https://github.com/astronomerio/astronomer-docs/blob/chargify/1.0/batch/standard-pipelines/chargify/to-redshift.md

**Comment by benjamingregory** [comment]
Tagging @JoshuaThompson to advise on general development and best practice for invoice solution.

@mbburch is currently expected to lead development.

**Comment by benjamingregory** [comment]
@mbburch Can you provide an update when you're able to start this?

**Comment by mbburch** [comment]
@benjamingregory I'm going to get started on a branch for this shortly.

**Comment by benjamingregory** [comment]
Hey @mbburch -- any update on this?

**Comment by mbburch** [comment]
@benjamingregory I haven't gotten to the invoices methods yet since I'd like to connect with others regarding the best way to go about it, but the others are added in. After the team switch, Mike had me spend a bit of time on this, but moved me to working on other things. If this is more of a priority, let me know and I can see where Mike would like me to focus.

**Comment by benjamingregory** [comment]
@mbburch Not a top priority right now -- just curious on the status. Thanks!

**Comment by ryw** [comment]
no more work on aries
